export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOAD_DOCUMENTS = "LOAD_DOCUMENTS";
export const DELETE_DOCUMENT = "DELETE_DOCUMENT";
export const CREATE_DOCUMENT = "CREATE_DOCUMENT";
export const SET_EDITOR_STATE = "SET_EDITOR_STATE";
export const SAVE_EDITOR_STATE = "SAVE_EDITOR_STATE";
